#include <algorithm>
#include <vector>
#include <string>
#include <iostream>
#include <math.h>
#include <stack>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
using namespace std;

void go(double i,int j)
{
    double t = 0;
    j = 2; //-1 at end
    while (t<i)
    {
        double c = 1/d;
        t+=c;
        j++;
    }
    j--;

}

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    double i;
    int j;
    cin >> i;
    go(i, j);

}


